all:
	clear
	echo "Para compilar o arquivo da aula, digita $ make aula\nPara compilar a pesquisa em diretorio, $ make pesquisa\nPara remover os arquivos compilados, digite make clean"
#Compilar pesquisa em diretórios
pesquisa:
	gcc pesquisa-em-diretorio.c -o pesquisa
#Compilar arquivo da aula:
aula:
	gcc diretorios.c -o diretorio
#Limpar arquivos compilados:
clean:
	rm -f pesquisa
	rm -f diretorio
